version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  db:
